=== cnanjo/OneModel/CQL/Src/cql-lm/schema/elm/modelinfo.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns="urn:hl7-org:elm-modelinfo:r1" targetNamespace="urn:hl7-org:elm-modelinfo:r1" elementFormDefault="qualified" attributeFormDefault="unqualified">
	<xs:element name="modelInfo" type="ModelInfo">
		<xs:annotation>
			<xs:documentation>Comment describing your root element</xs:documentation>
		</xs:annotation>
	</xs:element>
	<xs:complexType name="ModelInfo">
		<xs:sequence>
			<xs:element name="classInfo" type="ClassInfo" minOccurs="0" maxOccurs="unbounded"/>
		</xs:sequence>
		<xs:attribute name="name" type="xs:string" use="required"/>
		<xs:attribute name="url" type="xs:anyURI" use="required"/>
		<xs:attribute name="schemaLocation" type="xs:string" use="optional"/>
		<xs:attribute name="targetQualifier" type="xs:QName" use="optional"/>
		<xs:attribute name="patientClassName" type="xs:string" use="optional"/>
	</xs:complexType>
	<xs:complexType name="ClassInfo">
		<xs:attribute name="name" type="xs:string" use="required"/>
		<xs:attribute name="occurrenceAxis" type="xs:string" use="optional"/>
		<xs:attribute name="topicAxis" type="xs:string" use="required"/>
		<xs:attribute name="modalityAxis" type="xs:string" use="optional"/>
		<xs:attribute name="primaryCodeAttribute" type="xs:string" use="optional"/>
		<xs:attribute name="primaryDateAttribute" type="xs:string" use="optional"/>
	</xs:complexType>
</xs:schema>

=== cnanjo/OneModel/CQL/Src/java/quick/src/main/resources/org.hl7.fhir/quick-modelinfo.xml
<?xml version="1.0" encoding="UTF-8"?>
<modelInfo name="QUICK" xsi:schemaLocation="urn:hl7-org:elm-modelinfo:r1 modelinfo.xsd" xmlns="urn:hl7-org:elm-modelinfo:r1" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	url="http://org.hl7.fhir" patientClassName="Patient" schemaLocation="http://org.hl7.fhir quick.xsd" targetQualifier="quick">
	<classInfo name="PredictionOccurrence"  occurrenceAxis="Occurrence" topicAxis="Prediction" primaryCodeAttribute="outcome" primaryDateAttribute="observedAtTime"/>
	<classInfo name="ConditionOccurrence"  occurrenceAxis="Occurrence" topicAxis="Condition" primaryCodeAttribute="code" primaryDateAttribute="observedAtTime"/>
	<classInfo name="EncounterProposalOccurrence"  occurrenceAxis="Occurrence" topicAxis="Encounter" modalityAxis="Proposal" primaryCodeAttribute="class" primaryDateAttribute="proposedAtTime"/>
	<classInfo name="EncounterPerformanceOccurrence"  occurrenceAxis="Occurrence" topicAxis="Encounter" modalityAxis="Performance" primaryCodeAttribute="class" primaryDateAttribute="performanceTime"/>
	<classInfo name="MedicationTreatmentPerformanceOccurrence"  occurrenceAxis="Occurrence" topicAxis="MedicationTreatment" modalityAxis="Performance" primaryDateAttribute="performanceTime"/>
	<classInfo name="MedicationTreatmentOrderOccurrence"  occurrenceAxis="Occurrence" topicAxis="MedicationTreatment" modalityAxis="Order" primaryDateAttribute="orderedAtTime"/>
	<classInfo name="ProcedurePerformanceOccurrence"  occurrenceAxis="Occurrence" topicAxis="Procedure" modalityAxis="Performance" primaryCodeAttribute="procedureCode" primaryDateAttribute="performanceTime"/>
	<classInfo name="ProcedureOrderOccurrence"  occurrenceAxis="Occurrence" topicAxis="Procedure" modalityAxis="Order" primaryCodeAttribute="procedureCode" primaryDateAttribute="orderedAtTime"/>
	<classInfo name="SimpleObservationOccurrence"  occurrenceAxis="Occurrence" topicAxis="SimpleObservation" primaryCodeAttribute="code" primaryDateAttribute="observedAtTime"/>
	<classInfo name="DeviceUsePerformanceOccurrence"  occurrenceAxis="Occurrence" topicAxis="DeviceUse" modalityAxis="Performance" primaryDateAttribute="performanceTime"/>
	<classInfo name="DeviceUseProposalOccurrence"  occurrenceAxis="Occurrence" topicAxis="DeviceUse" modalityAxis="Proposal" primaryDateAttribute="proposedAtTime"/>
	<classInfo name="DeviceUseOrderOccurrence"  occurrenceAxis="Occurrence" topicAxis="DeviceUse" modalityAxis="Order" primaryDateAttribute="orderedAtTime"/>
	<classInfo name="ProcedureProposalOccurrence"  occurrenceAxis="Occurrence" topicAxis="Procedure" modalityAxis="Proposal" primaryCodeAttribute="procedureCode" primaryDateAttribute="proposedAtTime"/>
	<classInfo name="MedicationTreatmentProposalOccurrence"  occurrenceAxis="Occurrence" topicAxis="MedicationTreatment" modalityAxis="Proposal" primaryDateAttribute="proposedAtTime"/>
	<classInfo name="ObservationResultGroupOccurrence"  occurrenceAxis="Occurrence" topicAxis="ObservationResultGroup" primaryDateAttribute="observedAtTime"/>
	<classInfo name="DiagnosticImagingOrderOccurrence"  occurrenceAxis="Occurrence" topicAxis="DiagnosticImaging" modalityAxis="Order" primaryCodeAttribute="procedureCode" primaryDateAttribute="orderedAtTime"/>
	<classInfo name="DiagnosticImagingProposalOccurrence"  occurrenceAxis="Occurrence" topicAxis="DiagnosticImaging" modalityAxis="Proposal" primaryCodeAttribute="procedureCode" primaryDateAttribute="proposedAtTime"/>
	<classInfo name="DiagnosticImagingPerformanceOccurrence"  occurrenceAxis="Occurrence" topicAxis="DiagnosticImaging" modalityAxis="Performance" primaryCodeAttribute="procedureCode" primaryDateAttribute="performanceTime"/>
	<classInfo name="CommunicationProposalOccurrence"  occurrenceAxis="Occurrence" topicAxis="Communication" modalityAxis="Proposal" primaryDateAttribute="proposedAtTime"/>
	<classInfo name="CommunicationPerformanceOccurrence"  occurrenceAxis="Occurrence" topicAxis="Communication" modalityAxis="Performance" primaryDateAttribute="performanceTime"/>
</modelInfo>
